package cryptoassignment1;

/**
 *
 * @author Michael
 */
public class CryptoGUI extends javax.swing.JFrame {

    /**
     * Creates new form CryptoGUI
     */
    public CryptoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbn_Shift = new javax.swing.JRadioButton();
        rbn_Vigenere = new javax.swing.JRadioButton();
        rbn_MonoAlpha = new javax.swing.JRadioButton();
        rbn_Brute = new javax.swing.JRadioButton();
        btn_Activate = new javax.swing.JButton();
        btn_EXIT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Key = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_Output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFocusable(false);

        buttonGroup1.add(rbn_Shift);
        rbn_Shift.setText("Shift Cipher (Key)");

        buttonGroup1.add(rbn_Vigenere);
        rbn_Vigenere.setText("Vigenere Cipher (Key)");

        buttonGroup1.add(rbn_MonoAlpha);
        rbn_MonoAlpha.setText("Mono-Alphabetic");

        buttonGroup1.add(rbn_Brute);
        rbn_Brute.setText("Brute Force Crack");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rbn_Shift)
            .addComponent(rbn_Vigenere)
            .addComponent(rbn_MonoAlpha)
            .addComponent(rbn_Brute)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbn_Shift)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbn_Vigenere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbn_MonoAlpha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbn_Brute))
        );

        btn_Activate.setText("Activate");
        btn_Activate.setToolTipText("");
        btn_Activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActivateActionPerformed(evt);
            }
        });

        btn_EXIT.setText("EXIT");
        btn_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EXITActionPerformed(evt);
            }
        });

        jLabel1.setText("Input Text:");

        txt_Input.setColumns(255);

        jLabel2.setText("Key: (If needed)");

        txta_Output.setColumns(255);
        txta_Output.setRows(5);
        jScrollPane2.setViewportView(txta_Output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_EXIT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Activate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(txt_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Key, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Key, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(btn_Activate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_EXIT))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_EXITActionPerformed

    private void btn_ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActivateActionPerformed
        //Activate code based on active radiobutton
        String input = this.txt_Input.getText(); //read from Input box
        String key = this.txt_Key.getText(); //read from Key box
        
        if (this.rbn_Shift.isSelected()){
            int num_key = Integer.parseInt(key);
            CryptoAssignment1.Shift(input.toCharArray(),num_key);
        }
        else if (this.rbn_Vigenere.isSelected()){
            CryptoAssignment1.Vigenere(input.toCharArray(),key.toCharArray());
        }
        else if (this.rbn_MonoAlpha.isSelected()){
            CryptoAssignment1.MonoAlpha(input.toCharArray());
        }
        else if (this.rbn_Brute.isSelected()){
            CryptoAssignment1.Brute(input.toCharArray());
        }
        
    }//GEN-LAST:event_btn_ActivateActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Activate;
    private javax.swing.JButton btn_EXIT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbn_Brute;
    private javax.swing.JRadioButton rbn_MonoAlpha;
    private javax.swing.JRadioButton rbn_Shift;
    private javax.swing.JRadioButton rbn_Vigenere;
    private javax.swing.JTextField txt_Input;
    private javax.swing.JTextField txt_Key;
    public javax.swing.JTextArea txta_Output;
    // End of variables declaration//GEN-END:variables
}
